/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javaapplication3.Classdatabase;
import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author toshiba
 */
public class FormDataPelanggan extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormDataPelanggan
     */
    public FormDataPelanggan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtidentitas = new javax.swing.JTextField();
        radioktp = new javax.swing.JRadioButton();
        radiosim = new javax.swing.JRadioButton();
        txtnama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        radiolaki = new javax.swing.JRadioButton();
        radioperempuan = new javax.swing.JRadioButton();
        txthp = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttanggal = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblplg = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));

        jLabel2.setText("NO IDENTITAS");

        jLabel3.setText("NAMA");

        jLabel4.setText("ALAMAT");

        jLabel5.setText("JENIS KELAMIN");

        jLabel6.setText("NO HANDPHONE");

        jLabel7.setText("TANGGAL");

        txtidentitas.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtidentitasCaretUpdate(evt);
            }
        });

        buttonGroup1.add(radioktp);
        radioktp.setText("KTP");
        radioktp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioktpActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiosim);
        radiosim.setText("SIM");

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        buttonGroup2.add(radiolaki);
        radiolaki.setText("LAKI-LAKI");

        buttonGroup2.add(radioperempuan);
        radioperempuan.setText("PEREMPUAN");

        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnclose.setText("CLOSE");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        txtcari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtcariCaretUpdate(evt);
            }
        });

        jLabel8.setText("CARI DATA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcari)
                    .addComponent(txtnama)
                    .addComponent(jScrollPane1)
                    .addComponent(txthp)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(radiolaki, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioperempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtidentitas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radioktp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(radiosim, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                    .addComponent(txttanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(114, 114, 114)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtidentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioktp)
                    .addComponent(radiosim)
                    .addComponent(btnadd))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnedit)
                        .addGap(31, 31, 31)
                        .addComponent(btndelete))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(radiolaki)
                    .addComponent(radioperempuan))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txthp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclose))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 51));

        tblplg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblplg);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("FORM DATA PELANGGAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(226, 226, 226))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
    txtnama.setText("");
    txtalamat.setText("");
    txthp.setText("");
    //txttanggal;
    buttonGroup1.clearSelection();
    buttonGroup2.clearSelection();
    txtidentitas.setText("");
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        java.util.Date tgl_plg=(java.util.Date) this.txttanggal.getDate();
        String no_identitas = this.txtidentitas.getText();
        String nama = this.txtnama.getText();
        String j_identitas = null;
        if (radioktp.isSelected()){
            j_identitas = "KTP";
        } else {
            j_identitas = "SIM";
        }
        String jk = null;
        if (radiolaki.isSelected()){
            jk = "Laki-Laki";
        } else {
            jk = "Perempuan";
        }
        String alamat = this.txtalamat.getText();
        String nohp = this.txthp.getText();
        if(txtidentitas.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nomor Identitas tidak boleh kosong !");
        } else if (txtnama.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Kolom Nama tidak boleh kosong !");
        } else if (txtalamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom Alamat tidak boleh kosong !");
        } else if (txthp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom Nomor Handphone tidak boleh kosong !");
        } else {
            try{
                Connection c = Classdatabase.getkoneksi();
                String sql = "INSERT INTO pelanggan VALUES (?,?,?,?,?,?,?)";
                PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);
                p.setString(1, no_identitas);
                p.setString(2, j_identitas);
                p.setString(3, nama);
                p.setString(4, alamat);
                p.setString(5, jk);
                p.setString(6, nohp);
                p.setDate(7, new java.sql.Date(tgl_plg.getTime()));
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(this, "Berhasil menambahkan data");
            } catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            } finally {
                
            }
        }
        try {
            Connection c = Classdatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT no_identitas, j_identitas, nama, alamat, jk, nohp, tgl_plg FROM pelanggan";
            ResultSet r = s.executeQuery(sql);
            tblplg.setModel(DbUtils.resultSetToTableModel(r));
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void radioktpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioktpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioktpActionPerformed

    private void txtidentitasCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtidentitasCaretUpdate
        // GET NIK
        try{
                Connection c = Classdatabase.getkoneksi();
                Statement s = c.createStatement();
                String sql = "SELECT * FROM pelanggan WHERE no_identitas = '" + this.txtidentitas.getText() + "'";
                ResultSet r = s.executeQuery(sql);
                while (r.next()) {
                    this.txtnama.setText(r.getString(3));
                    if ("KTP".equalsIgnoreCase(r.getString("j_identitas"))){
                        radioktp.setSelected(true);
                    } else {
                        radiosim.setSelected(true);
                    }
                    if ("Laki-Laki".equalsIgnoreCase(r.getString("jk"))){
                        radiolaki.setSelected(true);
                    } else {
                        radioperempuan.setSelected(true);
                    }
                    this.txtalamat.setText(r.getString("alamat"));
                    this.txttanggal.setDate(r.getDate("tgl_plg"));
                    this.txthp.setText(r.getString("nohp"));
                }
                r.close();
                s.close();
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_txtidentitasCaretUpdate

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        java.util.Date tgl_plg=(java.util.Date) this.txttanggal.getDate();
        String no_identitas = this.txtidentitas.getText();
        String nama = this.txtnama.getText();
        String j_identitas = null;
        if (radioktp.isSelected()){
            j_identitas = "KTP";
        } else {
            j_identitas = "SIM";
        }
        String jk = null;
        if (radiolaki.isSelected()){
            jk = "Laki-Laki";
        } else {
            jk = "Perempuan";
        }
        String alamat = this.txtalamat.getText();
        String nohp = this.txthp.getText();
        if(txtidentitas.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nomor Identitas tidak boleh kosong !");
        } else if (txtnama.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Kolom Nama tidak boleh kosong !");
        } else if (txtalamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom Alamat tidak boleh kosong !");
        } else if (txthp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom Nomor Handphone tidak boleh kosong !");
        } else {
            try{
                Connection c = Classdatabase.getkoneksi();
                String sql = "UPDATE `pemrograman2`.`pelanggan` SET `j_identitas` = ?, `nama` = ?, `alamat` = ?, `jk` = ?, `nohp` = ?, `tgl_plg` = ? WHERE no_identitas = ?";
                PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);
                
                p.setString(1, j_identitas);
                p.setString(2, nama);
                p.setString(3, alamat);
                p.setString(4, jk);
                p.setString(5, nohp);
                p.setDate(6, new java.sql.Date(tgl_plg.getTime()));
                p.setString(7, no_identitas);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(this, "Berhasil update data");
            } catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            } finally {
                
            }
        }
        try {
            Connection c = Classdatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT no_identitas, j_identitas, nama, alamat, jk, nohp, tgl_plg FROM pelanggan";
            ResultSet r = s.executeQuery(sql);
            tblplg.setModel(DbUtils.resultSetToTableModel(r));
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        java.util.Date tgl_plg=(java.util.Date) this.txttanggal.getDate();
        String no_identitas = this.txtidentitas.getText();
            try{
                Connection c = Classdatabase.getkoneksi();
                String sql = "DELETE FROM `pemrograman2`.`pelanggan` WHERE no_identitas = ?";
                PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);
                p.setString(1, no_identitas);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(this, "Berhasil Hapus data");
            } catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            } finally {
                
            }
        try {
            Connection c = Classdatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT no_identitas, j_identitas, nama, alamat, jk, nohp, tgl_plg FROM pelanggan";
            ResultSet r = s.executeQuery(sql);
            tblplg.setModel(DbUtils.resultSetToTableModel(r));
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void txtcariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtcariCaretUpdate
        // TODO add your handling code here:
        //String no_identitas = this.txtcari.getText();
            try{
                Connection c = Classdatabase.getkoneksi();
                Statement s = c.createStatement();
                String sql = "SELECT * FROM pelanggan WHERE no_identitas LIKE '%" + this.txtcari.getText() + "%' OR j_identitas LIKE '%" + this.txtcari.getText() + "%' OR nama LIKE '%" + this.txtcari.getText() + "%' OR alamat LIKE '%" + this.txtcari.getText() + "%' OR nohp LIKE '%" + this.txtcari.getText() + "%' OR jk LIKE '%" + this.txtcari.getText() + "%' OR tgl_plg LIKE '%" + this.txtcari.getText() + "%'";
                ResultSet r = s.executeQuery(sql);
                tblplg.setModel(DbUtils.resultSetToTableModel(r));
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_txtcariCaretUpdate

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radioktp;
    private javax.swing.JRadioButton radiolaki;
    private javax.swing.JRadioButton radioperempuan;
    private javax.swing.JRadioButton radiosim;
    private javax.swing.JTable tblplg;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txthp;
    private javax.swing.JTextField txtidentitas;
    private javax.swing.JTextField txtnama;
    private com.toedter.calendar.JDateChooser txttanggal;
    // End of variables declaration//GEN-END:variables
}
