/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javaapplication3.Classdatabase;
import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author toshiba
 */
public class FormDataBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormDataBarang
     */
    public FormDataBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtkodebarang = new javax.swing.JTextField();
        txtnamabarang = new javax.swing.JTextField();
        txthargabeli = new javax.swing.JTextField();
        txthargajual = new javax.swing.JTextField();
        txtstok = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("FORM ENTRI DATA PENJUALAN BARANG");

        jLabel2.setText("KODE BARANG");

        jLabel3.setText("NAMA BARANG");

        jLabel4.setText("HARGA BELI");

        jLabel5.setText("HARGA JUAL");

        jLabel6.setText("STOK");

        txtkodebarang.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtkodebarangCaretUpdate(evt);
            }
        });

        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnclose.setText("CLOSE");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        txtcari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtcariCaretUpdate(evt);
            }
        });

        jButton6.setText("CARI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(168, 168, 168))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcari, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtkodebarang)
                            .addComponent(txtnamabarang)
                            .addComponent(txthargabeli)
                            .addComponent(txthargajual)
                            .addComponent(txtstok))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btnclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txthargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnedit))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txthargajual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclose))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        int saham1=0;
        String kodebarang = this.txtkodebarang.getText();
        String namabarang = this.txtnamabarang.getText();
        int h_beli1 = Integer.parseInt(txthargabeli.getText());
        String h_jual = this.txthargajual.getText();
        int stok1 = Integer.parseInt(txtstok.getText());
        
        saham1 = stok1*h_beli1;
        
        String h_beli = this.txthargabeli.getText();
        String stok = this.txtstok.getText();
        String saham = Integer.toString(saham1);
        
        if (txtkodebarang.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "KODE BARANG TIDAK BOLEH KOSONG");
        } else if (txtnamabarang.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "NAMA BARANG TIDAK BOLEH KOSONG");
        } else if (txthargabeli.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "HARGA BELI TIDAK BOLEH KOSONG");
        } else if (txthargajual.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "HARGA JUAL TIDAK BOLEH KOSONG");
        } else if (txtstok.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "STOK BARANG TIDAK BOLEH KOSONG");
        } else {
            
            try{
                Connection c = Classdatabase.getkoneksi();
                String sql = "INSERT INTO masterbarang VALUES (?,?,?,?,?,?)";
                PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);
                p.setString(1, kodebarang);
                p.setString(2, namabarang);
                p.setString(3, h_beli);
                p.setString(4, h_jual);
                p.setString(5, stok);
                p.setString(6, saham);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(this, "Berhasil menambahkan data");
            } catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            } finally {
                
            }    
        }
        
        try {
            Connection c = Classdatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT kodebarang, namabarang, h_beli, h_jual, stok, saham FROM masterbarang";
            ResultSet r = s.executeQuery(sql);
            tabel.setModel(DbUtils.resultSetToTableModel(r));
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        txtkodebarang.setText("");
        txtnamabarang.setText("");
        txthargajual.setText("");
        txthargabeli.setText("");
        txtstok.setText("");
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        String kodebarang = this.txtkodebarang.getText();
        String namabarang = this.txtnamabarang.getText();
        String h_beli = this.txthargabeli.getText();
        String h_jual = this.txthargajual.getText();
        String stok = this.txtstok.getText();
        
        int stok1 = Integer.parseInt(txtstok.getText());
        int h_beli1 = Integer.parseInt(txthargabeli.getText());
        int saham1= stok1 * h_beli1;
        String saham = Integer.toString(saham1);
        
        
        if(txtkodebarang.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Kode Barang tidak boleh kosong !");
        } else if (txtnamabarang.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Kolom Nama Barang tidak boleh kosong !");
        } else if (txthargabeli.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom Harga Beli tidak boleh kosong !");
        } else if (txthargajual.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom Harga Jual tidak boleh kosong !");
        } else if (txtstok.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom Stok tidak boleh kosong !");
        } else {
        
            try{
                Connection c = Classdatabase.getkoneksi();
                String sql = "UPDATE `pemrograman2`.`masterbarang` SET `namabarang` = ?, `h_beli` = ?, `h_jual` = ?, `stok` = ?, `saham` = ? WHERE kodebarang = ?";
                PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);
                
                p.setString(1, namabarang);
                p.setString(2, h_beli);
                p.setString(3, h_jual);
                p.setString(4, stok);
                p.setString(5, saham);
                p.setString(6, kodebarang);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(this, "Berhasil update data");
            } catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            } finally {
                
            }
        }    
        try {
            Connection c = Classdatabase.getkoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT kodebarang, namabarang, h_beli, h_jual, stok, saham FROM masterbarang";
            ResultSet r = s.executeQuery(sql);
            tabel.setModel(DbUtils.resultSetToTableModel(r));
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btneditActionPerformed

    private void txtkodebarangCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtkodebarangCaretUpdate
            try{
                Connection c = Classdatabase.getkoneksi();
                Statement s = c.createStatement();
                String sql = "SELECT * FROM masterbarang WHERE kodebarang = '" + this.txtkodebarang.getText() + "'";
                ResultSet r = s.executeQuery(sql);
                while (r.next()) {
                    this.txtnamabarang.setText(r.getString("namabarang"));
                    this.txthargabeli.setText(r.getString("h_beli"));
                    this.txthargajual.setText(r.getString("h_jual"));
                    this.txtstok.setText(r.getString("stok"));
                }
                r.close();
                s.close();
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        
        
    }//GEN-LAST:event_txtkodebarangCaretUpdate

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        String kodebarang = this.txtkodebarang.getText();
            try{
                Connection c = Classdatabase.getkoneksi();
                String sql = "DELETE FROM `pemrograman2`.`masterbarang` WHERE kodebarang = ?";
                PreparedStatement p = (PreparedStatement) c.prepareStatement(sql);
                p.setString(1, kodebarang);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(this, "Berhasil Hapus data", "Informasi", JOptionPane.YES_OPTION);
            } catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            } finally {
                
            }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void txtcariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtcariCaretUpdate
        try{
                Connection c = Classdatabase.getkoneksi();
                Statement s = c.createStatement();
                String sql = "SELECT * FROM masterbarang WHERE kodebarang LIKE '%" + this.txtcari.getText() + "%' OR namabarang LIKE '%" + this.txtcari.getText() + "%' OR h_beli LIKE '%" + this.txtcari.getText() + "%' OR h_jual LIKE '%" + this.txtcari.getText() + "%' OR stok LIKE '%" + this.txtcari.getText() + "%'";
                ResultSet r = s.executeQuery(sql);
                tabel.setModel(DbUtils.resultSetToTableModel(r));
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_txtcariCaretUpdate

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        
        this.setVisible(false);
    }//GEN-LAST:event_btncloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txthargabeli;
    private javax.swing.JTextField txthargajual;
    private javax.swing.JTextField txtkodebarang;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
